# Generated by Django 5.1.3 on 2024-12-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hottour',
            options={'verbose_name': 'Актуальные комната', 'verbose_name_plural': 'Актуальные комнаты'},
        ),
        migrations.AlterModelOptions(
            name='phototours',
            options={'verbose_name': 'Фото Номера', 'verbose_name_plural': 'Фотографии комнаты'},
        ),
        migrations.AlterModelOptions(
            name='tours',
            options={'verbose_name': 'Номер', 'verbose_name_plural': 'Номера'},
        ),
        migrations.AddField(
            model_name='tours',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tours',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tours',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название номера'),
        ),
    ]
